In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('shots_data.csv')

In [3]:
df

       team     x     y  fgmade
0    Team A -23.1   3.5       0
1    Team A   0.0  25.1       1
2    Team A   0.5   1.0       1
3    Team A  -5.6   5.2       0
4    Team A   4.0  14.5       1
..      ...   ...   ...     ...
555  Team B   7.8  24.7       0
556  Team B  10.1   1.4       1
557  Team B -17.8  -0.1       0
558  Team B  22.6   2.9       0
559  Team B  -0.7  14.7       1

[560 rows x 4 columns]

In [4]:
TeamB=df[df['team']=='Team B'].reset_index()

In [5]:
TeamB

     index    team     x     y  fgmade
0      280  Team B   2.5   6.2       0
1      281  Team B   7.4  18.3       1
2      282  Team B   1.1   0.1       0
3      283  Team B  -1.6  25.6       0
4      284  Team B -14.4  21.7       1
..     ...     ...   ...   ...     ...
275    555  Team B   7.8  24.7       0
276    556  Team B  10.1   1.4       1
277    557  Team B -17.8  -0.1       0
278    558  Team B  22.6   2.9       0
279    559  Team B  -0.7  14.7       1

[280 rows x 5 columns]

In [6]:
C3y_TeamB=TeamB[TeamB.y <= 7.8]
C3y_TeamB

     index    team     x    y  fgmade
0      280  Team B   2.5  6.2       0
2      282  Team B   1.1  0.1       0
15     295  Team B   2.2  0.2       1
18     298  Team B -22.3  2.6       1
24     304  Team B   1.4  7.6       1
..     ...     ...   ...  ...     ...
271    551  Team B   8.4  5.7       0
273    553  Team B   1.1  2.3       1
276    556  Team B  10.1  1.4       1
277    557  Team B -17.8 -0.1       0
278    558  Team B  22.6  2.9       0

[132 rows x 5 columns]

In [7]:
C3xp_TeamB=C3y_TeamB[(C3y_TeamB.x <= 23.75) & (C3y_TeamB.x >= 22.00)]
C3xp_TeamB

     index    team     x    y  fgmade
32     312  Team B  22.8  1.1       0
71     351  Team B  22.6  2.8       1
113    393  Team B  23.1 -0.1       0
160    440  Team B  22.7  0.9       0
181    461  Team B  23.7  0.9       0
183    463  Team B  22.8  3.3       0
192    472  Team B  23.2  2.0       0
193    473  Team B  23.1  2.9       1
257    537  Team B  23.6  6.3       0
264    544  Team B  22.6  2.2       0
278    558  Team B  22.6  2.9       0

In [8]:
C3xn_TeamB=C3y_TeamB[(C3y_TeamB.x >= -23.75) & (C3y_TeamB.x <= -22.00)]
C3xn_TeamB

     index    team     x    y  fgmade
18     298  Team B -22.3  2.6       1
27     307  Team B -23.1  2.9       0
65     345  Team B -23.4  7.1       0
104    384  Team B -22.8  1.9       0
154    434  Team B -23.0  0.0       0
190    470  Team B -22.6  2.5       0
197    477  Team B -22.8  0.8       1
228    508  Team B -22.9 -1.5       0
267    547  Team B -23.0 -0.6       0

In [9]:
C3_TeamB= C3xn_TeamB.append([C3xp_TeamB])
C3_TeamB

     index    team     x    y  fgmade
18     298  Team B -22.3  2.6       1
27     307  Team B -23.1  2.9       0
65     345  Team B -23.4  7.1       0
104    384  Team B -22.8  1.9       0
154    434  Team B -23.0  0.0       0
190    470  Team B -22.6  2.5       0
197    477  Team B -22.8  0.8       1
228    508  Team B -22.9 -1.5       0
267    547  Team B -23.0 -0.6       0
32     312  Team B  22.8  1.1       0
71     351  Team B  22.6  2.8       1
113    393  Team B  23.1 -0.1       0
160    440  Team B  22.7  0.9       0
181    461  Team B  23.7  0.9       0
183    463  Team B  22.8  3.3       0
192    472  Team B  23.2  2.0       0
193    473  Team B  23.1  2.9       1
257    537  Team B  23.6  6.3       0
264    544  Team B  22.6  2.2       0
278    558  Team B  22.6  2.9       0

In [10]:
TwoPy_TeamB=TeamB[TeamB.y < 23.75]
TwoPy_TeamB

     index    team     x     y  fgmade
0      280  Team B   2.5   6.2       0
1      281  Team B   7.4  18.3       1
2      282  Team B   1.1   0.1       0
4      284  Team B -14.4  21.7       1
5      285  Team B -10.6  23.5       1
..     ...     ...   ...   ...     ...
274    554  Team B  20.5  14.1       0
276    556  Team B  10.1   1.4       1
277    557  Team B -17.8  -0.1       0
278    558  Team B  22.6   2.9       0
279    559  Team B  -0.7  14.7       1

[242 rows x 5 columns]

In [11]:
TwoPx_TeamB=TwoPy_TeamB[(TwoPy_TeamB.x < 22.00) & (TwoPy_TeamB.x > -22.00)]
TwoPx_TeamB

     index    team     x     y  fgmade
0      280  Team B   2.5   6.2       0
1      281  Team B   7.4  18.3       1
2      282  Team B   1.1   0.1       0
4      284  Team B -14.4  21.7       1
5      285  Team B -10.6  23.5       1
..     ...     ...   ...   ...     ...
273    553  Team B   1.1   2.3       1
274    554  Team B  20.5  14.1       0
276    556  Team B  10.1   1.4       1
277    557  Team B -17.8  -0.1       0
279    559  Team B  -0.7  14.7       1

[217 rows x 5 columns]

In [12]:
TwoP_TeamB=TwoPx_TeamB
TwoP_TeamB

     index    team     x     y  fgmade
0      280  Team B   2.5   6.2       0
1      281  Team B   7.4  18.3       1
2      282  Team B   1.1   0.1       0
4      284  Team B -14.4  21.7       1
5      285  Team B -10.6  23.5       1
..     ...     ...   ...   ...     ...
273    553  Team B   1.1   2.3       1
274    554  Team B  20.5  14.1       0
276    556  Team B  10.1   1.4       1
277    557  Team B -17.8  -0.1       0
279    559  Team B  -0.7  14.7       1

[217 rows x 5 columns]

In [14]:
NCR3_TeamB=pd.concat([TwoP_TeamB,C3_TeamB, TeamB]).drop_duplicates(keep=False)
NCR3_TeamB

     index    team     x     y  fgmade
3      283  Team B  -1.6  25.6       0
11     291  Team B   0.1  25.9       1
19     299  Team B   4.9  25.2       1
23     303  Team B -23.1   8.4       1
31     311  Team B  -1.2  26.9       0
35     315  Team B   9.4  24.1       0
38     318  Team B  -3.6  29.7       0
49     329  Team B   9.7  25.6       1
66     346  Team B  -8.7  24.4       0
77     357  Team B  23.8  -1.2       1
79     359  Team B   1.8  26.6       0
88     368  Team B   1.0  29.2       1
90     370  Team B  13.2  24.3       1
92     372  Team B   5.8  27.4       1
103    383  Team B   4.0  25.7       0
106    386  Team B  23.4  10.3       0
108    388  Team B   7.7  27.0       1
112    392  Team B  -1.5  26.4       0
114    394  Team B   1.3  27.7       0
115    395  Team B  12.1  24.6       0
122    402  Team B  -0.2  24.6       0
133    413  Team B  13.4  26.1       0
136    416  Team B  -6.5  24.9       1
141    421  Team B  -0.4  25.9       0
144    424  Team B   4.5  26.2       1
145    425  Team B   9.5  24.0       0
152    432  Team B   0.3  24.6       0
161    441  Team B  -0.1  25.6       0
165    445  Team B  -1.9  25.7       0
172    452  Team B   7.8  24.3       1
179    459  Team B   9.8  24.7       0
185    465  Team B  -0.4  24.5       1
186    466  Team B   1.8  26.4       0
188    468  Team B  22.3   9.4       1
191    471  Team B   1.0  25.5       0
204    484  Team B   7.4  24.4       0
205    485  Team B  -7.5  23.9       0
206    486  Team B  11.6  24.3       0
207    487  Team B  -3.2  25.7       1
217    497  Team B  -0.5  25.6       1
255    535  Team B -22.5  10.4       0
258    538  Team B  11.1  24.0       0
275    555  Team B   7.8  24.7       0

In [19]:
Shots_Attempted_TwoPoint= len(TwoP_TeamB.index)/len(TeamB.index)*100
Shots_Attempted_TwoPoint

77.5

In [17]:
Shots_Attempted_NonCorner3= len(NCR3_TeamB.index)/len(TeamB.index)*100
Shots_Attempted_NonCorner3

15.357142857142858

In [20]:
Shots_Attempted_Corner3= len(C3_TeamB.index)/len(TeamB.index)*100
Shots_Attempted_Corner3

7.142857142857142

In [21]:
Twopoint_made = sum(TwoP_TeamB['fgmade']==True)
Twopoint_made

95

In [22]:
Corner3_made = sum(C3_TeamB['fgmade']==True)
Corner3_made

4

In [23]:
NonCorner3_made = sum(NCR3_TeamB['fgmade']==True)
NonCorner3_made

16

In [24]:
EFG_TwoPoint = ((Twopoint_made)+(0.5*(NonCorner3_made+Corner3_made)))/len(TwoP_TeamB.index)*100
EFG_TwoPoint

48.38709677419355

In [25]:
EFG_Corner3 = ((Corner3_made)+(0.5*(NonCorner3_made+Corner3_made)))/len(C3_TeamB.index)*100
EFG_Corner3

70.0

In [26]:
EFG_NonCorner3 = ((NonCorner3_made)+(0.5*(NonCorner3_made+Corner3_made)))/len(NCR3_TeamB.index)*100
EFG_NonCorner3

60.46511627906976