In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('shots_data.csv')

In [3]:
df

       team     x     y  fgmade
0    Team A -23.1   3.5       0
1    Team A   0.0  25.1       1
2    Team A   0.5   1.0       1
3    Team A  -5.6   5.2       0
4    Team A   4.0  14.5       1
..      ...   ...   ...     ...
555  Team B   7.8  24.7       0
556  Team B  10.1   1.4       1
557  Team B -17.8  -0.1       0
558  Team B  22.6   2.9       0
559  Team B  -0.7  14.7       1

[560 rows x 4 columns]

In [4]:
TeamA=df[df['team']=='Team A'].reset_index()

In [5]:
TeamB=df[df['team']=='Team B'].reset_index()

In [7]:
TeamA

     index    team     x     y  fgmade
0        0  Team A -23.1   3.5       0
1        1  Team A   0.0  25.1       1
2        2  Team A   0.5   1.0       1
3        3  Team A  -5.6   5.2       0
4        4  Team A   4.0  14.5       1
..     ...     ...   ...   ...     ...
275    275  Team A  23.0   4.7       1
276    276  Team A  -3.0  25.4       0
277    277  Team A  -8.0   2.6       1
278    278  Team A  -7.6   1.7       0
279    279  Team A  -5.5   6.2       1

[280 rows x 5 columns]

In [8]:
TeamB

     index    team     x     y  fgmade
0      280  Team B   2.5   6.2       0
1      281  Team B   7.4  18.3       1
2      282  Team B   1.1   0.1       0
3      283  Team B  -1.6  25.6       0
4      284  Team B -14.4  21.7       1
..     ...     ...   ...   ...     ...
275    555  Team B   7.8  24.7       0
276    556  Team B  10.1   1.4       1
277    557  Team B -17.8  -0.1       0
278    558  Team B  22.6   2.9       0
279    559  Team B  -0.7  14.7       1

[280 rows x 5 columns]

In [38]:
C3y_TeamA=TeamA[TeamA.y <= 7.8]
C3y_TeamA

     index    team     x    y  fgmade
0        0  Team A -23.1  3.5       0
2        2  Team A   0.5  1.0       1
3        3  Team A  -5.6  5.2       0
5        5  Team A -13.6  4.0       1
6        6  Team A  -9.0  7.2       1
..     ...     ...   ...  ...     ...
272    272  Team A -23.3  1.7       0
275    275  Team A  23.0  4.7       1
277    277  Team A  -8.0  2.6       1
278    278  Team A  -7.6  1.7       0
279    279  Team A  -5.5  6.2       1

[138 rows x 5 columns]

In [47]:
C3xp_TeamA=C3y_TeamA[(C3y_TeamA.x <= 23.75) & (C3y_TeamA.x >= 22.00)]
C3xp_TeamA

     index    team     x    y  fgmade
11      11  Team A  22.3  3.5       0
22      22  Team A  22.5  1.8       1
24      24  Team A  23.5  2.4       0
92      92  Team A  22.8  3.6       1
171    171  Team A  22.6  4.0       0
185    185  Team A  23.0  2.2       0
223    223  Team A  22.9  6.1       1
230    230  Team A  23.7  3.8       1
235    235  Team A  22.8 -0.9       0
242    242  Team A  23.4  1.8       1
275    275  Team A  23.0  4.7       1

In [48]:
C3xn_TeamA=C3y_TeamA[(C3y_TeamA.x >= -23.75) & (C3y_TeamA.x <= -22.00)]
C3xn_TeamA

     index    team     x    y  fgmade
0        0  Team A -23.1  3.5       0
96      96  Team A -22.9  2.4       0
205    205  Team A -23.4  0.9       1
229    229  Team A -23.4  4.2       0
232    232  Team A -22.8  3.1       1
233    233  Team A -23.0  7.6       0
239    239  Team A -23.5  3.7       0
257    257  Team A -23.6  4.8       0
272    272  Team A -23.3  1.7       0

In [52]:
C3_TeamA= C3xn_TeamA.append([C3xp_TeamA])
C3_TeamA

     index    team     x    y  fgmade
0        0  Team A -23.1  3.5       0
96      96  Team A -22.9  2.4       0
205    205  Team A -23.4  0.9       1
229    229  Team A -23.4  4.2       0
232    232  Team A -22.8  3.1       1
233    233  Team A -23.0  7.6       0
239    239  Team A -23.5  3.7       0
257    257  Team A -23.6  4.8       0
272    272  Team A -23.3  1.7       0
11      11  Team A  22.3  3.5       0
22      22  Team A  22.5  1.8       1
24      24  Team A  23.5  2.4       0
92      92  Team A  22.8  3.6       1
171    171  Team A  22.6  4.0       0
185    185  Team A  23.0  2.2       0
223    223  Team A  22.9  6.1       1
230    230  Team A  23.7  3.8       1
235    235  Team A  22.8 -0.9       0
242    242  Team A  23.4  1.8       1
275    275  Team A  23.0  4.7       1

In [74]:
TwoPy_TeamA=TeamA[TeamA.y < 23.75]
TwoPy_TeamA

     index    team     x     y  fgmade
0        0  Team A -23.1   3.5       0
2        2  Team A   0.5   1.0       1
3        3  Team A  -5.6   5.2       0
4        4  Team A   4.0  14.5       1
5        5  Team A -13.6   4.0       1
..     ...     ...   ...   ...     ...
274    274  Team A -13.3  20.7       0
275    275  Team A  23.0   4.7       1
277    277  Team A  -8.0   2.6       1
278    278  Team A  -7.6   1.7       0
279    279  Team A  -5.5   6.2       1

[238 rows x 5 columns]

In [75]:
TwoPx_TeamA=TwoPy_TeamA[(TwoPy_TeamA.x < 22.00) & (TwoPy_TeamA.x > -22.00)]
TwoPx_TeamA

     index    team     x     y  fgmade
2        2  Team A   0.5   1.0       1
3        3  Team A  -5.6   5.2       0
4        4  Team A   4.0  14.5       1
5        5  Team A -13.6   4.0       1
6        6  Team A  -9.0   7.2       1
..     ...     ...   ...   ...     ...
271    271  Team A   1.6  13.9       0
274    274  Team A -13.3  20.7       0
277    277  Team A  -8.0   2.6       1
278    278  Team A  -7.6   1.7       0
279    279  Team A  -5.5   6.2       1

[214 rows x 5 columns]

In [76]:
TwoP_TeamA=TwoPx_TeamA

In [77]:
TwoP_TeamA

     index    team     x     y  fgmade
2        2  Team A   0.5   1.0       1
3        3  Team A  -5.6   5.2       0
4        4  Team A   4.0  14.5       1
5        5  Team A -13.6   4.0       1
6        6  Team A  -9.0   7.2       1
..     ...     ...   ...   ...     ...
271    271  Team A   1.6  13.9       0
274    274  Team A -13.3  20.7       0
277    277  Team A  -8.0   2.6       1
278    278  Team A  -7.6   1.7       0
279    279  Team A  -5.5   6.2       1

[214 rows x 5 columns]

In [96]:
NCR3_TeamA=pd.concat([TwoP_TeamA,C3_TeamA, TeamA]).drop_duplicates(keep=False)

In [97]:
NCR3_TeamA

     index    team     x     y  fgmade
1        1  Team A   0.0  25.1       1
18      18  Team A   2.3  26.2       0
30      30  Team A  -8.2  23.9       0
44      44  Team A  13.1  25.6       0
46      46  Team A   5.5  26.4       0
47      47  Team A   3.1  25.1       0
55      55  Team A -10.6  26.1       0
59      59  Team A  10.3  24.8       0
74      74  Team A   1.2  26.4       0
78      78  Team A  -7.9  24.3       1
83      83  Team A  -0.9  26.2       1
85      85  Team A  22.8  10.3       0
89      89  Team A  23.0   8.1       1
105    105  Team A  15.0  24.8       0
110    110  Team A -13.6  24.1       1
111    111  Team A   4.1  25.6       0
130    130  Team A  -9.2  24.7       0
131    131  Team A -10.5  24.5       0
135    135  Team A  -9.4  25.7       0
137    137  Team A  11.3  24.3       0
141    141  Team A  -3.5  26.1       1
143    143  Team A   4.8  26.3       0
147    147  Team A   4.0  25.6       0
151    151  Team A  23.2   9.9       1
158    158  Team A  -3.3  24.7       1
163    163  Team A   9.1  24.2       1
165    165  Team A  12.5  24.4       0
169    169  Team A  -3.4  27.7       0
191    191  Team A   5.5  25.6       0
195    195  Team A  23.0  12.4       0
202    202  Team A  -2.7  25.9       1
204    204  Team A   2.2  26.6       1
206    206  Team A   2.5  25.5       1
222    222  Team A   4.0  24.9       1
225    225  Team A   2.6  25.2       0
226    226  Team A   0.6  27.0       0
228    228  Team A  -9.1  23.9       0
234    234  Team A -12.7  25.0       1
240    240  Team A  -9.5  25.8       1
241    241  Team A  -9.2  25.2       0
245    245  Team A  -2.2  26.1       0
255    255  Team A  -0.6  26.1       1
256    256  Team A   7.9  24.5       0
263    263  Team A -11.3  26.1       0
273    273  Team A   4.0  26.5       1
276    276  Team A  -3.0  25.4       0

In [125]:
Shots_Attempted_TwoPoint= len(TwoP_TeamA.index)/len(TeamA.index)*100
Shots_Attempted_TwoPoint

76.42857142857142

In [124]:
Shots_Attempted_NonCorner3= len(NCR3_TeamA.index)/len(TeamA.index)*100
Shots_Attempted_NonCorner3

16.428571428571427

In [123]:
Shots_Attempted_Corner3= len(C3_TeamA.index)/len(TeamA.index)*100
Shots_Attempted_Corner3

7.142857142857142

In [113]:
Twopoint_made = sum(TwoP_TeamA['fgmade']==True)
Twopoint_made

80

In [114]:
Corner3_made = sum(C3_TeamA['fgmade']==True)
Corner3_made

8

In [115]:
NonCorner3_made = sum(NCR3_TeamA['fgmade']==True)
NonCorner3_made

17

In [122]:
EFG_TwoPoint = ((Twopoint_made)+(0.5*(NonCorner3_made+Corner3_made)))/len(TwoP_TeamA.index)*100
EFG_TwoPoint

43.22429906542056

In [121]:
EFG_Corner3 = ((Corner3_made)+(0.5*(NonCorner3_made+Corner3_made)))/len(C3_TeamA.index)*100
EFG_Corner3

102.49999999999999

In [120]:
EFG_NonCorner3 = ((NonCorner3_made)+(0.5*(NonCorner3_made+Corner3_made)))/len(NCR3_TeamA.index)*100
EFG_NonCorner3

64.13043478260869